### ISSUE TITLE
Game improvement tip: more types of fishes

### ISSUE THREAD

**Issue by SWel1a** [Flagro/BotFishingGame#1]
I hope you won't sleep on your project and keep develop it! Pretty interesting game but I'd like to see more variety in fishes.

**Comment by Flagro** [comment]
Hi @SWel1a!

Thank you for your suggestion! I have expanded the list of items that can be caught in the fishing game to make it more diverse and entertaining. Now, players can catch not only a variety of fish but also encounter amusing surprises like a boot, an empty bottle, and even a sunken treasure chest!

Here’s a glimpse of some of the new items added:

Various types of fish like Clownfish, Barracuda, Pufferfish, etc.
Aquatic creatures like Jellyfish, Seahorse, Octopus, etc.
Fun and unexpected items like an Old Can, a Plastic Bag, a Pirate Hat, etc.
You can see the changes in [this commit](https://github.com/Flagro/BotFishingGame/commit/3fb992d4de2a5b43dc869b10eff3464ac37b12a4)

Thank you once again for your valuable input! 

Happy Fishing! 🎮
